### ISSUE TITLE
Feature request:  function argon2_needs_rehash

### ISSUE THREAD

**Issue by sptndc** [charlesportwoodii/php-argon2-ext#6]
Please add a function argon2_needs_rehash. Thanks

**Comment by charlesportwoodii** [comment]
`argon2_needs_rehash` isn't a Argon2 native function.

If you're using this library for password hashing, I strongly recommend that you migrate either to PHP 7.2 `password_hash`, or if you're on PHP 7.0 or 7.1 use [Sodium 2.x](https://github.com/jedisct1/libsodium-php) instead, as it supersedes this library. `sodium_crypto_pwhash_str_needs_rehash` would be the method that you're looking for.
